apiVersion: v2
name: sematic-server
description: Sematic AI Server
type: application
version: 1.1.9
appVersion: v0.29.1
maintainers:
  - name: sematic-ai
    url: https://github.com/sematic-ai/sematic/
